### PR TITLE
Updated EvoluData Icon

### PR DESCRIPTION
**Pull request by bilalsiddiq**
Updated EvoluData icon and fixed text on Service Providers page.

### CODE REVIEW

**Comment by guusdk** [comment]
Thanks Bilal. Apart from whitespace, I don't see any changes to text, even though you mention that in your commit message. Is that intended?

**Comment by bilalsiddiq** [comment]
Pade was not printing correctly before. Had to paste it again raw.

**Comment by bilalsiddiq** [comment]
Hi Guus,

Thank you for approving the pull request.
https://www.igniterealtime.org/support/service_providers.jsp has now
updated EvoluData icon. But still Pàdé is not appearing correctly in our
description text of EvoluData. Can you please help fix that?

Regards,
Bilal

**Comment by guusdk** [comment]
Hi Bilal! This is probably due to the website using some old technology in
the background. It is probably safest to use the HTML encoded characters,
like &agrave; and &eacute;

**Pull request merged**
