### PR TITLE
 WEB-72 remove discontinued projects 

### PR DESCRIPTION
**Pull request by wrooot**

### CODE REVIEW

**Comment by guusdk** [comment]
Not sure if we should remove these completely.

They're clearly marked "discontinued", but someone might have value for these.

**Comment by wrooot** [comment]
Well, a week or so ago i think you said we can hide them, bu still leave the associated forums. Both projects use Flash. Which should be officially dead next year. Of course, one can still use it (internally or so). But we can't support it, fix problems, etc. There will be more and more issues with it as time goes. They are marked as discontinued, but we still receive questions about them.

**Comment by wrooot** [comment]
Anyway, still have messed this commit. So will need to close it probably. So, are we leaving them on the site? @akrherz @speedy01 what do you think?

**Comment by wrooot** [comment]
Oh, if we will decide to keep them, we should add word Flash to SparkWeb description, so it would scare people away :)

**Comment by speedy01** [comment]
maybe instead of removing them completely, we just stop offering the binaries. Link people to the source code instead.  I'd hate for people to download and use sparkweb  not realizing that it was last updated in 2008, and assuming it was recently dicontinued.

**Pull request closed without merging**
